### ISSUE TITLE
Template editorconfig vs E

### ISSUE THREAD

**Issue by plindman** [kendo-labs/generator-kendo-ui#1]
When generating, the generator looks for file editorConfig but the file in templates folder is editorconfig. Probably very easy to fix.

Error: ENOENT, no such file or directory '~local/lib/node_modules/generator-kendo-ui/app/templates/editorConfig'

~/dev/kendoui-test $ ls ~/local/lib/node_modules/generator-kendo-ui/app/templates/
app.build.js  bowerrc       gitattributes  Gruntfile.js  jshintrc       spa
_bower.json   editorconfig  gitignore      index.html    _package.json

**Comment by lamuertepeluda** [comment]
Same error here (MacBook Pro, OSX Mavericks, Node v0.10.28, yo v1.1.2)

``` bash
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/generator-kendo-ui/app/templates/editorConfig'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at KendoUIGenerator.prepCopy (/usr/local/lib/node_modules/generator-kendo-ui/node_modules/yeoman-generator/lib/actions/actions.js:54:13)
    at KendoUIGenerator.copy (/usr/local/lib/node_modules/generator-kendo-ui/node_modules/yeoman-generator/lib/actions/actions.js:82:23)
    at KendoUIGenerator.editorConfig (/usr/local/lib/node_modules/generator-kendo-ui/app/index.js:86:8)
    at /usr/local/lib/node_modules/generator-kendo-ui/node_modules/yeoman-generator/lib/base.js:316:43
    at /usr/local/lib/node_modules/generator-kendo-ui/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-kendo-ui/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-kendo-ui/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at /usr/local/lib/node_modules/generator-kendo-ui/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25
```

**Comment by lamuertepeluda** [comment]
ok just rename app/templates/editorconfig to app/templates/editorConfig and it works!
